<?php

use App\Http\Controllers\Api\V1\Accounting\AccountController;
use App\Http\Controllers\Api\V1\Accounting\AccountingPeriodController;
use App\Http\Controllers\Api\V1\Accounting\AccountMappingController;
use App\Http\Controllers\Api\V1\Accounting\CustomerController;
use App\Http\Controllers\Api\V1\Accounting\FbrInvoiceController;
use App\Http\Controllers\Api\V1\Accounting\FinancialReportController;
use App\Http\Controllers\Api\V1\Accounting\InventoryActionController;
use App\Http\Controllers\Api\V1\Accounting\InventoryItemController;
use App\Http\Controllers\Api\V1\Accounting\InventoryReportController;
use App\Http\Controllers\Api\V1\Accounting\InvoiceActionController;
use App\Http\Controllers\Api\V1\Accounting\InvoiceController;
use App\Http\Controllers\Api\V1\Accounting\JournalController;
use App\Http\Controllers\Api\V1\Accounting\LedgerController;
use App\Http\Controllers\Api\V1\Accounting\PayableController;
use App\Http\Controllers\Api\V1\Accounting\PurchaseOrderActionController;
use App\Http\Controllers\Api\V1\Accounting\PurchaseOrderController;
use App\Http\Controllers\Api\V1\Accounting\PurchaseReceiptController;
use App\Http\Controllers\Api\V1\Accounting\ReceivableController;
use App\Http\Controllers\Api\V1\Accounting\SupplierBillActionController;
use App\Http\Controllers\Api\V1\Accounting\SupplierBillController;
use App\Http\Controllers\Api\V1\Accounting\SupplierController;
use App\Http\Controllers\Api\V1\Accounting\WarehouseController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\Banking\BankReconciliationController;
use App\Http\Controllers\Api\V1\Banking\BankStatementImportController;
use App\Http\Controllers\Api\V1\Banking\BankTransactionController;
use App\Http\Controllers\Api\V1\Banking\CashFlowController;
use App\Http\Controllers\Api\V1\Banking\FinancialAccountController;
use App\Http\Controllers\Api\V1\Banking\GatewaySettlementController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:login');

    Route::middleware('auth:sanctum')->group(function (): void {
        Route::get('auth/me', [AuthController::class, 'current']);
        Route::post('auth/logout', [AuthController::class, 'logout']);

        Route::middleware('company')->group(function (): void {
            Route::get('accounting/accounts/selectable', [AccountController::class, 'selectable']);
            Route::patch('accounting/accounts/{account}/status', [AccountController::class, 'status']);
            Route::apiResource('accounting/accounts', AccountController::class)->except('destroy');
            Route::apiResource('accounting/periods', AccountingPeriodController::class)->only(['index', 'store', 'update']);
            Route::post('accounting/journals/post', [JournalController::class, 'post']);
            Route::post('accounting/journals/{journal}/post', [JournalController::class, 'post']);
            Route::post('accounting/journals/{journal}/reverse', [JournalController::class, 'reverse']);
            Route::apiResource('accounting/journals', JournalController::class)->only(['index', 'show', 'store', 'update']);
            Route::get('accounting/ledger', [LedgerController::class, 'index']);
            Route::get('accounting/ledger/trial-balance', [LedgerController::class, 'trialBalance']);
            Route::get('accounting/reports/trial-balance', [FinancialReportController::class, 'trialBalance']);
            Route::get('accounting/reports/profit-and-loss', [FinancialReportController::class, 'profitAndLoss']);
            Route::get('accounting/reports/balance-sheet', [FinancialReportController::class, 'balanceSheet']);
            Route::get('accounting/settings/account-mappings', [AccountMappingController::class, 'index']);
            Route::patch('accounting/settings/account-mappings/{key}', [AccountMappingController::class, 'update']);
            Route::apiResource('accounting/customers', CustomerController::class);
            Route::post('accounting/invoices/{invoice}/post', [InvoiceActionController::class, 'post']);
            Route::post('accounting/invoices/{invoice}/void', [InvoiceActionController::class, 'void']);
            Route::apiResource('accounting/invoices', InvoiceController::class);
            Route::get('accounting/fbr/invoices', [FbrInvoiceController::class, 'index']);
            Route::post('accounting/fbr/invoices/{invoice}/submit', [FbrInvoiceController::class, 'submit']);
            Route::get('accounting/receivables/customers', [ReceivableController::class, 'customers']);
            Route::get('accounting/receivables/invoices', [ReceivableController::class, 'invoices']);
            Route::get('accounting/receivables/payments', [ReceivableController::class, 'payments']);
            Route::post('accounting/receivables/invoices/{invoice}/payments', [ReceivableController::class, 'recordPayment']);
            Route::get('accounting/receivables/aging', [ReceivableController::class, 'aging']);
            Route::get('accounting/receivables/customers/{customer}/ledger', [ReceivableController::class, 'ledger']);
            Route::get('accounting/receivables/customers/{customer}/statement', [ReceivableController::class, 'statement']);
            Route::apiResource('accounting/payables/suppliers', SupplierController::class);
            Route::post('purchases/orders/{order}/submit', [PurchaseOrderActionController::class, 'submit']);
            Route::post('purchases/orders/{order}/approve', [PurchaseOrderActionController::class, 'approve']);
            Route::post('purchases/orders/{order}/reject', [PurchaseOrderActionController::class, 'reject']);
            Route::post('purchases/orders/{order}/cancel', [PurchaseOrderActionController::class, 'cancel']);
            Route::post('purchases/orders/{order}/convert-to-bill', [PurchaseOrderActionController::class, 'convertToBill']);
            Route::get('purchases/orders/{order}/receipts', [PurchaseReceiptController::class, 'index']);
            Route::post('purchases/orders/{order}/receipts', [PurchaseReceiptController::class, 'store']);
            Route::get('purchases/receipts/{receipt}', [PurchaseReceiptController::class, 'show']);
            Route::apiResource('purchases/orders', PurchaseOrderController::class)->parameters(['orders' => 'order']);
            Route::post('accounting/payables/bills/{bill}/post', [SupplierBillActionController::class, 'post']);
            Route::post('accounting/payables/bills/{bill}/void', [SupplierBillActionController::class, 'void']);
            Route::apiResource('accounting/payables/bills', SupplierBillController::class)->parameters(['bills' => 'bill']);
            Route::get('accounting/payables/summary/suppliers', [PayableController::class, 'suppliers']);
            Route::get('accounting/payables/open-bills', [PayableController::class, 'bills']);
            Route::get('accounting/payables/payments', [PayableController::class, 'payments']);
            Route::post('accounting/payables/bills/{bill}/payments', [PayableController::class, 'recordPayment']);
            Route::get('accounting/payables/aging', [PayableController::class, 'aging']);
            Route::get('accounting/payables/suppliers/{supplier}/ledger', [PayableController::class, 'ledger']);
            Route::get('accounting/payables/suppliers/{supplier}/statement', [PayableController::class, 'statement']);
            Route::apiResource('inventory/items', InventoryItemController::class)->parameters(['items' => 'item']);
            Route::apiResource('inventory/warehouses', WarehouseController::class);
            Route::post('inventory/transfers', [InventoryActionController::class, 'transfer'])->name('inventory.transfer');
            Route::post('inventory/adjustments', [InventoryActionController::class, 'adjustment'])->name('inventory.adjustment');
            Route::post('inventory/cost-adjustments', [InventoryActionController::class, 'costAdjustment'])->name('inventory.cost-adjustment');
            Route::post('inventory/customer-returns/{invoice}', [InventoryActionController::class, 'customerReturn'])->name('inventory.customer-return');
            Route::post('inventory/supplier-returns/{receipt}', [InventoryActionController::class, 'supplierReturn'])->name('inventory.supplier-return');
            Route::get('accounting/inventory/ledger', [InventoryReportController::class, 'ledger'])->name('inventory.ledger');
            Route::get('accounting/inventory/valuation', [InventoryReportController::class, 'valuation'])->name('inventory.valuation');
            Route::get('accounting/inventory/layers', [InventoryReportController::class, 'layers'])->name('inventory.layers');
            Route::get('accounting/inventory/items/{item}/layers', [InventoryReportController::class, 'layers'])->name('inventory.item-layers');
            Route::get('accounting/inventory/cogs', [InventoryReportController::class, 'cogs'])->name('inventory.cogs');
            Route::get('accounting/inventory/low-stock', [InventoryReportController::class, 'lowStock'])->name('inventory.low-stock');
            Route::get('accounting/inventory/reconciliation', [InventoryReportController::class, 'reconciliation'])->name('inventory.reconciliation');
            Route::apiResource('banking/accounts', FinancialAccountController::class)
                ->parameters(['accounts' => 'financial_account'])
                ->names('banking.accounts')
                ->only(['index', 'store', 'show', 'update']);
            Route::get('banking/statement-imports', [BankStatementImportController::class, 'index']);
            Route::post('banking/statement-imports/preview', [BankStatementImportController::class, 'preview']);
            Route::post('banking/statement-imports/{statement_import}/confirm', [BankStatementImportController::class, 'confirm']);
            Route::get('banking/transactions', [BankTransactionController::class, 'index']);
            Route::get('banking/transactions/{bank_transaction}/suggestions', [BankTransactionController::class, 'suggestions']);
            Route::post('banking/transactions/{bank_transaction}/match', [BankTransactionController::class, 'match']);
            Route::post('banking/matches/{match}/unmatch', [BankTransactionController::class, 'unmatch']);
            Route::post('banking/transactions/{bank_transaction}/classify', [BankTransactionController::class, 'classify']);
            Route::post('banking/transactions/{bank_transaction}/customer-receipt', [BankTransactionController::class, 'customerReceipt']);
            Route::post('banking/transactions/{bank_transaction}/supplier-payment', [BankTransactionController::class, 'supplierPayment']);
            Route::post('banking/cash-transactions', [BankTransactionController::class, 'cash']);
            Route::post('banking/internal-transfers', [BankTransactionController::class, 'transfer']);
            Route::get('banking/reconciliations', [BankReconciliationController::class, 'index']);
            Route::post('banking/reconciliations', [BankReconciliationController::class, 'store']);
            Route::get('banking/reconciliations/{reconciliation}', [BankReconciliationController::class, 'show']);
            Route::post('banking/reconciliations/{reconciliation}/complete', [BankReconciliationController::class, 'complete']);
            Route::post('banking/reconciliations/{reconciliation}/reopen', [BankReconciliationController::class, 'reopen']);
            Route::get('banking/settlements', [GatewaySettlementController::class, 'index']);
            Route::post('banking/settlements', [GatewaySettlementController::class, 'store']);
            Route::get('banking/settlements/{settlement}', [GatewaySettlementController::class, 'show']);
            Route::post('banking/settlements/{settlement}/post', [GatewaySettlementController::class, 'post']);
            Route::get('banking/cash-position', [CashFlowController::class, 'current']);
            Route::get('banking/cash-forecast', [CashFlowController::class, 'forecast']);
            Route::get('banking/cash-movement', [CashFlowController::class, 'movement']);
            Route::get('banking/accounts/{financial_account}/bank-gl', [CashFlowController::class, 'bankGl']);
        });
    });
});
