<?php

use App\Http\Controllers\Api\V1\Accounting\AccountController;
use App\Http\Controllers\Api\V1\Accounting\AccountingCloseController;
use App\Http\Controllers\Api\V1\Accounting\AccountingPeriodController;
use App\Http\Controllers\Api\V1\Accounting\AccountMappingController;
use App\Http\Controllers\Api\V1\Accounting\CustomerController;
use App\Http\Controllers\Api\V1\Accounting\FbrInvoiceController;
use App\Http\Controllers\Api\V1\Accounting\FinancialReportController;
use App\Http\Controllers\Api\V1\Accounting\InventoryActionController;
use App\Http\Controllers\Api\V1\Accounting\InventoryItemController;
use App\Http\Controllers\Api\V1\Accounting\InventoryReportController;
use App\Http\Controllers\Api\V1\Accounting\InvoiceActionController;
use App\Http\Controllers\Api\V1\Accounting\InvoiceController;
use App\Http\Controllers\Api\V1\Accounting\JournalController;
use App\Http\Controllers\Api\V1\Accounting\LedgerController;
use App\Http\Controllers\Api\V1\Accounting\PayableController;
use App\Http\Controllers\Api\V1\Accounting\PurchaseOrderActionController;
use App\Http\Controllers\Api\V1\Accounting\PurchaseOrderController;
use App\Http\Controllers\Api\V1\Accounting\PurchaseReceiptController;
use App\Http\Controllers\Api\V1\Accounting\ReceivableController;
use App\Http\Controllers\Api\V1\Accounting\SupplierBillActionController;
use App\Http\Controllers\Api\V1\Accounting\SupplierBillController;
use App\Http\Controllers\Api\V1\Accounting\SupplierController;
use App\Http\Controllers\Api\V1\Accounting\WarehouseController;
use App\Http\Controllers\Api\V1\AccountProfileController;
use App\Http\Controllers\Api\V1\Ai\AiActionProposalController;
use App\Http\Controllers\Api\V1\Ai\AiConversationController;
use App\Http\Controllers\Api\V1\Ai\AiEvaluationController;
use App\Http\Controllers\Api\V1\Ai\AiProviderConfigurationController;
use App\Http\Controllers\Api\V1\Ai\AiUsageController;
use App\Http\Controllers\Api\V1\Ai\CalendarIntelligenceController;
use App\Http\Controllers\Api\V1\Ai\IntelligenceAnalyticsController;
use App\Http\Controllers\Api\V1\Ai\IntelligenceOperationsController;
use App\Http\Controllers\Api\V1\Ai\IntelligenceScenarioController;
use App\Http\Controllers\Api\V1\Ai\KnowledgeSourceController;
use App\Http\Controllers\Api\V1\Ai\PrioritySignalController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\Banking\BankReconciliationController;
use App\Http\Controllers\Api\V1\Banking\BankStatementImportController;
use App\Http\Controllers\Api\V1\Banking\BankTransactionController;
use App\Http\Controllers\Api\V1\Banking\CashFlowController;
use App\Http\Controllers\Api\V1\Banking\FinancialAccountController;
use App\Http\Controllers\Api\V1\Banking\GatewaySettlementController;
use App\Http\Controllers\Api\V1\Crm\CrmAccountController;
use App\Http\Controllers\Api\V1\Crm\CrmActivityController;
use App\Http\Controllers\Api\V1\Crm\CrmContactController;
use App\Http\Controllers\Api\V1\Crm\CrmDealController;
use App\Http\Controllers\Api\V1\Crm\CrmImportController;
use App\Http\Controllers\Api\V1\Crm\CrmLeadController;
use App\Http\Controllers\Api\V1\Crm\CrmPipelineController;
use App\Http\Controllers\Api\V1\Crm\CrmReportController;
use App\Http\Controllers\Api\V1\Crm\CrmScoreController;
use App\Http\Controllers\Api\V1\Crm\CrmTagController;
use App\Http\Controllers\Api\V1\EmployeeIdentityController;
use App\Http\Controllers\Api\V1\Fbr\FbrConfigurationController;
use App\Http\Controllers\Api\V1\Fbr\FbrReferenceDataController;
use App\Http\Controllers\Api\V1\Fbr\LegacyMigrationController;
use App\Http\Controllers\Api\V1\Fbr\PakistanFbrInvoiceController;
use App\Http\Controllers\Api\V1\Outreach\EmailProviderConnectionController;
use App\Http\Controllers\Api\V1\Outreach\EmailSendingIdentityController;
use App\Http\Controllers\Api\V1\Outreach\EmailTemplateController;
use App\Http\Controllers\Api\V1\Outreach\OutreachEnrollmentController;
use App\Http\Controllers\Api\V1\Outreach\OutreachMessageController;
use App\Http\Controllers\Api\V1\Outreach\OutreachPublicController;
use App\Http\Controllers\Api\V1\Outreach\OutreachReportController;
use App\Http\Controllers\Api\V1\Outreach\OutreachSequenceController;
use App\Http\Controllers\Api\V1\Outreach\OutreachSuppressionController;
use App\Http\Controllers\Api\V1\Payroll\EmployeeController;
use App\Http\Controllers\Api\V1\Payroll\EmployeePayrollProfileController;
use App\Http\Controllers\Api\V1\Payroll\PayrollBatchController;
use App\Http\Controllers\Api\V1\Payroll\PayrollComponentController;
use App\Http\Controllers\Api\V1\Payroll\PayrollEntryController;
use App\Http\Controllers\Api\V1\Payroll\PayrollLiabilityController;
use App\Http\Controllers\Api\V1\Payroll\PayrollPaymentController;
use App\Http\Controllers\Api\V1\Payroll\PayrollPeriodController;
use App\Http\Controllers\Api\V1\Payroll\PayrollReportController;
use App\Http\Controllers\Api\V1\Planning\BudgetController;
use App\Http\Controllers\Api\V1\Planning\FiscalYearController;
use App\Http\Controllers\Api\V1\Planning\ForecastController;
use App\Http\Controllers\Api\V1\Platform\AuditController;
use App\Http\Controllers\Api\V1\Platform\CompanyController;
use App\Http\Controllers\Api\V1\Platform\CompanyExportController;
use App\Http\Controllers\Api\V1\Platform\CompanySettingController;
use App\Http\Controllers\Api\V1\Platform\CompanyUserController;
use App\Http\Controllers\Api\V1\Platform\DocumentController;
use App\Http\Controllers\Api\V1\Platform\EmployeeLinkController;
use App\Http\Controllers\Api\V1\Platform\EmployeeLinkOptionController;
use App\Http\Controllers\Api\V1\Platform\InvitationController;
use App\Http\Controllers\Api\V1\Platform\NavigationPreferenceController;
use App\Http\Controllers\Api\V1\Platform\NotificationController;
use App\Http\Controllers\Api\V1\Platform\RoleController;
use App\Http\Controllers\Api\V1\Platform\SecurityController;
use App\Http\Controllers\Api\V1\Platform\SubscriptionController;
use App\Http\Controllers\Api\V1\Platform\SystemController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('health/live', [SystemController::class, 'live'])->name('health.live');
    Route::get('health/ready', [SystemController::class, 'ready'])->name('health.ready');
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::post('auth/forgot-password', [AuthController::class, 'requestPasswordReset'])->middleware('throttle:password-reset')->name('password.email');
    Route::post('auth/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:password-reset')->name('password.update');
    Route::post('invitations/accept', [InvitationController::class, 'accept'])->middleware('throttle:invitations')->name('invitations.accept');
    Route::post('outreach/providers/{connection}/webhook', [EmailProviderConnectionController::class, 'webhook'])->middleware('throttle:sensitive')->name('outreach.providers.webhook');
    Route::get('outreach/open/{message}/{token}', [OutreachPublicController::class, 'open'])->middleware('throttle:sensitive')->name('outreach.open');
    Route::get('outreach/click/{token}', [OutreachPublicController::class, 'click'])->middleware('throttle:sensitive')->name('outreach.click');
    Route::match(['get', 'post'], 'outreach/unsubscribe/{token}', [OutreachPublicController::class, 'unsubscribe'])->middleware('throttle:sensitive')->name('outreach.unsubscribe');

    Route::middleware('auth:sanctum')->group(function (): void {
        Route::get('auth/me', [AuthController::class, 'current']);
        Route::get('auth/profile', [AccountProfileController::class, 'show'])->name('auth.profile.show');
        Route::patch('auth/profile', [AccountProfileController::class, 'update'])->middleware('throttle:sensitive')->name('auth.profile.update');
        Route::post('auth/change-password', [AccountProfileController::class, 'changePassword'])->middleware('throttle:password-change')->name('auth.change-password');
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::post('auth/switch-company', [AuthController::class, 'switchCompany'])->middleware('throttle:company-switch');
        Route::post('platform/companies', [CompanyController::class, 'store'])->middleware('throttle:company-create')->name('platform.companies.store');

        Route::middleware('company')->group(function (): void {
            Route::get('employee/me', [EmployeeIdentityController::class, 'show'])->name('employee.me');
            Route::get('platform/navigation', [NavigationPreferenceController::class, 'index'])->name('platform.navigation.index');
            Route::put('platform/navigation/{item}', [NavigationPreferenceController::class, 'update'])->middleware('throttle:sensitive')->name('platform.navigation.update');
            Route::delete('platform/navigation/{item}', [NavigationPreferenceController::class, 'reset'])->middleware('throttle:sensitive')->name('platform.navigation.reset');
            Route::get('ai/tools', [AiConversationController::class, 'tools'])->name('ai.tools.index');
            Route::get('ai/conversations', [AiConversationController::class, 'index'])->name('ai.conversations.index');
            Route::post('ai/conversations', [AiConversationController::class, 'store'])->name('ai.conversations.store');
            Route::get('ai/conversations/{conversation}', [AiConversationController::class, 'show'])->name('ai.conversations.show');
            Route::post('ai/conversations/{conversation}/messages', [AiConversationController::class, 'message'])->middleware('throttle:ai')->name('ai.conversations.messages.store');
            Route::post('ai/conversations/{conversation}/archive', [AiConversationController::class, 'archive'])->name('ai.conversations.archive');
            Route::get('ai/knowledge-sources', [KnowledgeSourceController::class, 'index'])->name('ai.knowledge-sources.index');
            Route::post('ai/knowledge-sources', [KnowledgeSourceController::class, 'store'])->middleware('throttle:ai')->name('ai.knowledge-sources.store');
            Route::get('ai/knowledge-sources/{source}', [KnowledgeSourceController::class, 'show'])->name('ai.knowledge-sources.show');
            Route::put('ai/knowledge-sources/{source}', [KnowledgeSourceController::class, 'update'])->middleware('throttle:ai')->name('ai.knowledge-sources.update');
            Route::post('ai/knowledge-sources/{source}/ingestions', [KnowledgeSourceController::class, 'ingest'])->middleware('throttle:ai')->name('ai.knowledge-sources.ingest');
            Route::delete('ai/knowledge-sources/{source}', [KnowledgeSourceController::class, 'destroy'])->name('ai.knowledge-sources.destroy');
            Route::get('ai/action-proposals', [AiActionProposalController::class, 'index'])->name('ai.action-proposals.index');
            Route::post('ai/action-proposals', [AiActionProposalController::class, 'store'])->middleware('throttle:ai')->name('ai.action-proposals.store');
            Route::get('ai/action-proposals/{proposal}', [AiActionProposalController::class, 'show'])->name('ai.action-proposals.show');
            Route::post('ai/action-proposals/{proposal}/approve', [AiActionProposalController::class, 'approve'])->middleware('throttle:ai')->name('ai.action-proposals.approve');
            Route::post('ai/action-proposals/{proposal}/reject', [AiActionProposalController::class, 'reject'])->middleware('throttle:ai')->name('ai.action-proposals.reject');
            Route::post('ai/action-proposals/{proposal}/execute', [AiActionProposalController::class, 'execute'])->middleware('throttle:ai')->name('ai.action-proposals.execute');
            Route::get('ai/provider-configuration', [AiProviderConfigurationController::class, 'show'])->name('ai.provider-configuration.show');
            Route::put('ai/provider-configuration', [AiProviderConfigurationController::class, 'update'])->middleware('throttle:ai')->name('ai.provider-configuration.update');
            Route::get('ai/usage', [AiUsageController::class, 'index'])->name('ai.usage.index');
            Route::get('ai/evaluations', [AiEvaluationController::class, 'index'])->name('ai.evaluations.index');
            Route::post('ai/evaluations', [AiEvaluationController::class, 'store'])->name('ai.evaluations.store');
            Route::post('ai/evaluations/{case}/runs', [AiEvaluationController::class, 'run'])->middleware('throttle:ai')->name('ai.evaluations.run');
            Route::get('ai/intelligence/priorities', [PrioritySignalController::class, 'index'])->name('ai.intelligence.priorities.index');
            Route::get('ai/intelligence/priorities/{signal}', [PrioritySignalController::class, 'show'])->name('ai.intelligence.priorities.show');
            Route::patch('ai/intelligence/priorities/{signal}', [PrioritySignalController::class, 'update'])->name('ai.intelligence.priorities.update');
            Route::get('ai/intelligence/anomalies', [IntelligenceAnalyticsController::class, 'anomalies'])->name('ai.intelligence.anomalies.index');
            Route::get('ai/intelligence/forecasts', [IntelligenceAnalyticsController::class, 'forecasts'])->name('ai.intelligence.forecasts.index');
            Route::get('ai/intelligence/briefing', [IntelligenceAnalyticsController::class, 'briefing'])->middleware('throttle:ai')->name('ai.intelligence.briefing.show');
            Route::get('ai/intelligence/evaluations', [IntelligenceAnalyticsController::class, 'evaluations'])->name('ai.intelligence.evaluations.index');
            Route::get('ai/intelligence/scenarios', [IntelligenceScenarioController::class, 'index'])->name('ai.intelligence.scenarios.index');
            Route::post('ai/intelligence/scenarios', [IntelligenceScenarioController::class, 'store'])->name('ai.intelligence.scenarios.store');
            Route::get('ai/intelligence/scenarios/{scenario}', [IntelligenceScenarioController::class, 'show'])->name('ai.intelligence.scenarios.show');
            Route::post('ai/intelligence/refresh', [IntelligenceOperationsController::class, 'refresh'])->middleware('throttle:ai')->name('ai.intelligence.refresh');
            Route::get('ai/intelligence/runs', [IntelligenceOperationsController::class, 'runs'])->name('ai.intelligence.runs.index');
            Route::get('ai/intelligence/observability', [IntelligenceOperationsController::class, 'observability'])->name('ai.intelligence.observability.show');
            Route::get('ai/intelligence/provider-reconciliations', [IntelligenceOperationsController::class, 'reconciliations'])->name('ai.intelligence.provider-reconciliations.index');
            Route::post('ai/intelligence/provider-reconciliations', [IntelligenceOperationsController::class, 'importReconciliation'])->name('ai.intelligence.provider-reconciliations.store');
            Route::get('ai/intelligence/calendar/capability', [CalendarIntelligenceController::class, 'capability'])->name('ai.intelligence.calendar.capability');
            Route::get('ai/intelligence/calendar/events', [CalendarIntelligenceController::class, 'events'])->name('ai.intelligence.calendar.events.index');
            Route::post('ai/intelligence/calendar/synchronize', [CalendarIntelligenceController::class, 'synchronize'])->name('ai.intelligence.calendar.synchronize');
            Route::get('ai/intelligence/calendar/events/{event}/context', [CalendarIntelligenceController::class, 'meetingContext'])->name('ai.intelligence.calendar.context');
            Route::get('platform/users', [CompanyUserController::class, 'index'])->name('platform.users.index');
            Route::get('platform/employee-link-options', [EmployeeLinkOptionController::class, 'index'])->name('platform.employee-link-options.index');
            Route::get('platform/users/{membership}', [CompanyUserController::class, 'show'])->name('platform.users.show');
            Route::get('platform/users/{membership}/employee-link', [EmployeeLinkController::class, 'show'])->name('platform.users.employee-link.show');
            Route::put('platform/users/{membership}/employee-link', [EmployeeLinkController::class, 'update'])->middleware('throttle:sensitive')->name('platform.users.employee-link.update');
            Route::delete('platform/users/{membership}/employee-link', [EmployeeLinkController::class, 'destroy'])->middleware('throttle:sensitive')->name('platform.users.employee-link.destroy');
            Route::put('platform/users/{membership}/roles', [CompanyUserController::class, 'updateRoles'])->name('platform.users.roles');
            Route::patch('platform/users/{membership}/status', [CompanyUserController::class, 'updateStatus'])->name('platform.users.status');
            Route::delete('platform/users/{membership}', [CompanyUserController::class, 'destroy'])->name('platform.users.destroy');
            Route::get('platform/invitations', [InvitationController::class, 'index'])->name('platform.invitations.index');
            Route::post('platform/invitations', [InvitationController::class, 'store'])->middleware('throttle:invitations')->name('platform.invitations.store');
            Route::post('platform/invitations/{invitation}/resend', [InvitationController::class, 'resend'])->middleware('throttle:invitations')->name('platform.invitations.resend');
            Route::post('platform/invitations/{invitation}/revoke', [InvitationController::class, 'revoke'])->name('platform.invitations.revoke');
            Route::get('platform/roles', [RoleController::class, 'index'])->name('platform.roles.index');
            Route::post('platform/roles', [RoleController::class, 'store'])->name('platform.roles.store');
            Route::put('platform/roles/{role}', [RoleController::class, 'update'])->name('platform.roles.update');
            Route::post('platform/roles/{role}/clone', [RoleController::class, 'clone'])->name('platform.roles.clone');
            Route::post('platform/roles/{role}/archive', [RoleController::class, 'archive'])->name('platform.roles.archive');
            Route::get('platform/settings', [CompanySettingController::class, 'show'])->name('platform.settings.show');
            Route::put('platform/settings', [CompanySettingController::class, 'update'])->name('platform.settings.update');
            Route::post('platform/settings/logo', [CompanySettingController::class, 'logo'])->middleware('throttle:uploads')->name('platform.settings.logo');
            Route::get('platform/subscription', [SubscriptionController::class, 'show'])->name('platform.subscription.show');
            Route::put('platform/subscription', [SubscriptionController::class, 'update'])->name('platform.subscription.update');
            Route::put('platform/entitlements/{module}', [SubscriptionController::class, 'updateEntitlement'])->name('platform.entitlements.update');
            Route::post('platform/plans', [SubscriptionController::class, 'storePlan'])->name('platform.plans.store');
            Route::get('platform/notifications', [NotificationController::class, 'index'])->name('platform.notifications.index');
            Route::post('platform/notifications/read-all', [NotificationController::class, 'readAll'])->name('platform.notifications.read-all');
            Route::post('platform/notifications/{notification}/read', [NotificationController::class, 'read'])->name('platform.notifications.read');
            Route::get('platform/notification-preferences', [NotificationController::class, 'preferences'])->name('platform.notification-preferences.index');
            Route::put('platform/notification-preferences', [NotificationController::class, 'updatePreferences'])->name('platform.notification-preferences.update');
            Route::get('platform/documents', [DocumentController::class, 'index'])->name('platform.documents.index');
            Route::post('platform/documents', [DocumentController::class, 'store'])->middleware('throttle:uploads')->name('platform.documents.store');
            Route::get('platform/documents/{document}/download', [DocumentController::class, 'download'])->name('platform.documents.download');
            Route::delete('platform/documents/{document}', [DocumentController::class, 'destroy'])->name('platform.documents.destroy');
            Route::get('platform/audit', [AuditController::class, 'index'])->name('platform.audit.index');
            Route::get('platform/security', [SecurityController::class, 'index'])->name('platform.security.index');
            Route::delete('platform/security/sessions/{session}', [SecurityController::class, 'revokeSession'])->name('platform.security.sessions.destroy');
            Route::delete('platform/security/sessions', [SecurityController::class, 'revokeOthers'])->name('platform.security.sessions.destroy-others');
            Route::get('platform/system/failed-jobs', [SystemController::class, 'failedJobs'])->name('platform.system.failed-jobs');
            Route::post('platform/system/failed-jobs/{uuid}/retry', [SystemController::class, 'retryJob'])->name('platform.system.failed-jobs.retry');
            Route::get('platform/system/schedule', [SystemController::class, 'schedule'])->name('platform.system.schedule');
            Route::get('platform/exports', [CompanyExportController::class, 'index'])->name('platform.exports.index');
            Route::post('platform/exports', [CompanyExportController::class, 'store'])->name('platform.exports.store');
            Route::get('platform/exports/{export}/download', [CompanyExportController::class, 'download'])->name('platform.exports.download');
            Route::get('accounting/accounts/selectable', [AccountController::class, 'selectable']);
            Route::patch('accounting/accounts/{account}/status', [AccountController::class, 'status']);
            Route::apiResource('accounting/accounts', AccountController::class)->except('destroy');
            Route::apiResource('accounting/periods', AccountingPeriodController::class)->only(['index', 'store', 'update']);
            Route::post('accounting/journals/post', [JournalController::class, 'post']);
            Route::post('accounting/journals/{journal}/post', [JournalController::class, 'post']);
            Route::post('accounting/journals/{journal}/reverse', [JournalController::class, 'reverse']);
            Route::apiResource('accounting/journals', JournalController::class)->only(['index', 'show', 'store', 'update']);
            Route::get('accounting/ledger', [LedgerController::class, 'index']);
            Route::get('accounting/ledger/trial-balance', [LedgerController::class, 'trialBalance']);
            Route::get('accounting/reports/trial-balance', [FinancialReportController::class, 'trialBalance']);
            Route::get('accounting/reports/profit-and-loss', [FinancialReportController::class, 'profitAndLoss']);
            Route::get('accounting/reports/balance-sheet', [FinancialReportController::class, 'balanceSheet']);
            Route::get('accounting/reports/comparative', [FinancialReportController::class, 'comparative'])->name('accounting.reports.comparative');
            Route::get('accounting/settings/account-mappings', [AccountMappingController::class, 'index']);
            Route::patch('accounting/settings/account-mappings/{key}', [AccountMappingController::class, 'update']);
            Route::apiResource('accounting/customers', CustomerController::class);
            Route::post('accounting/invoices/{invoice}/post', [InvoiceActionController::class, 'post']);
            Route::post('accounting/invoices/{invoice}/void', [InvoiceActionController::class, 'void']);
            Route::apiResource('accounting/invoices', InvoiceController::class);
            Route::get('accounting/fbr/invoices', [FbrInvoiceController::class, 'index']);
            Route::post('accounting/fbr/invoices/{invoice}/submit', [FbrInvoiceController::class, 'submit'])->middleware('throttle:sensitive');
            Route::get('pakistan-fbr/invoices', [PakistanFbrInvoiceController::class, 'index'])->name('pakistan-fbr.invoices.index');
            Route::post('pakistan-fbr/invoices', [PakistanFbrInvoiceController::class, 'store'])->middleware('throttle:sensitive')->name('pakistan-fbr.invoices.store');
            Route::get('pakistan-fbr/invoices/{invoice}', [PakistanFbrInvoiceController::class, 'show'])->name('pakistan-fbr.invoices.show');
            Route::patch('pakistan-fbr/invoices/{invoice}', [PakistanFbrInvoiceController::class, 'update'])->middleware('throttle:sensitive')->name('pakistan-fbr.invoices.update');
            Route::post('pakistan-fbr/invoices/{invoice}/submit', [PakistanFbrInvoiceController::class, 'submit'])->middleware('throttle:sensitive')->name('pakistan-fbr.invoices.submit');
            Route::post('pakistan-fbr/invoices/{invoice}/retry', [PakistanFbrInvoiceController::class, 'retry'])->middleware('throttle:sensitive')->name('pakistan-fbr.invoices.retry');
            Route::get('pakistan-fbr/invoices/{invoice}/attempts', [PakistanFbrInvoiceController::class, 'attempts'])->name('pakistan-fbr.invoices.attempts');
            Route::get('pakistan-fbr/configuration', [FbrConfigurationController::class, 'show'])->name('pakistan-fbr.configuration.show');
            Route::put('pakistan-fbr/configuration', [FbrConfigurationController::class, 'update'])->middleware('throttle:sensitive')->name('pakistan-fbr.configuration.update');
            Route::get('pakistan-fbr/reference-data', [FbrReferenceDataController::class, 'index'])->name('pakistan-fbr.reference-data.index');
            Route::get('pakistan-fbr/migrations', [LegacyMigrationController::class, 'index'])->name('pakistan-fbr.migrations.index');
            Route::get('pakistan-fbr/migrations/{run}', [LegacyMigrationController::class, 'show'])->name('pakistan-fbr.migrations.show');
            Route::get('pakistan-fbr/migrations/{run}/exceptions', [LegacyMigrationController::class, 'exceptions'])->name('pakistan-fbr.migrations.exceptions.index');
            Route::patch('pakistan-fbr/migration-exceptions/{exception}', [LegacyMigrationController::class, 'resolve'])->name('pakistan-fbr.migration-exceptions.update');
            Route::get('pakistan-fbr/historical-invoices/{invoice}/evidence', [LegacyMigrationController::class, 'evidence'])->name('pakistan-fbr.historical-invoices.evidence.index');
            Route::get('accounting/receivables/customers', [ReceivableController::class, 'customers']);
            Route::get('accounting/receivables/invoices', [ReceivableController::class, 'invoices']);
            Route::get('accounting/receivables/payments', [ReceivableController::class, 'payments']);
            Route::post('accounting/receivables/invoices/{invoice}/payments', [ReceivableController::class, 'recordPayment']);
            Route::get('accounting/receivables/aging', [ReceivableController::class, 'aging']);
            Route::get('accounting/receivables/customers/{customer}/ledger', [ReceivableController::class, 'ledger']);
            Route::get('accounting/receivables/customers/{customer}/statement', [ReceivableController::class, 'statement']);
            Route::apiResource('accounting/payables/suppliers', SupplierController::class);
            Route::post('purchases/orders/{order}/submit', [PurchaseOrderActionController::class, 'submit']);
            Route::post('purchases/orders/{order}/approve', [PurchaseOrderActionController::class, 'approve']);
            Route::post('purchases/orders/{order}/reject', [PurchaseOrderActionController::class, 'reject']);
            Route::post('purchases/orders/{order}/cancel', [PurchaseOrderActionController::class, 'cancel']);
            Route::post('purchases/orders/{order}/convert-to-bill', [PurchaseOrderActionController::class, 'convertToBill']);
            Route::get('purchases/orders/{order}/receipts', [PurchaseReceiptController::class, 'index']);
            Route::post('purchases/orders/{order}/receipts', [PurchaseReceiptController::class, 'store']);
            Route::get('purchases/receipts/{receipt}', [PurchaseReceiptController::class, 'show']);
            Route::apiResource('purchases/orders', PurchaseOrderController::class)->parameters(['orders' => 'order']);
            Route::post('accounting/payables/bills/{bill}/post', [SupplierBillActionController::class, 'post']);
            Route::post('accounting/payables/bills/{bill}/void', [SupplierBillActionController::class, 'void']);
            Route::apiResource('accounting/payables/bills', SupplierBillController::class)->parameters(['bills' => 'bill']);
            Route::get('accounting/payables/summary/suppliers', [PayableController::class, 'suppliers']);
            Route::get('accounting/payables/open-bills', [PayableController::class, 'bills']);
            Route::get('accounting/payables/payments', [PayableController::class, 'payments']);
            Route::post('accounting/payables/bills/{bill}/payments', [PayableController::class, 'recordPayment']);
            Route::get('accounting/payables/aging', [PayableController::class, 'aging']);
            Route::get('accounting/payables/suppliers/{supplier}/ledger', [PayableController::class, 'ledger']);
            Route::get('accounting/payables/suppliers/{supplier}/statement', [PayableController::class, 'statement']);
            Route::apiResource('inventory/items', InventoryItemController::class)->parameters(['items' => 'item']);
            Route::apiResource('inventory/warehouses', WarehouseController::class);
            Route::post('inventory/transfers', [InventoryActionController::class, 'transfer'])->name('inventory.transfer');
            Route::post('inventory/adjustments', [InventoryActionController::class, 'adjustment'])->name('inventory.adjustment');
            Route::post('inventory/cost-adjustments', [InventoryActionController::class, 'costAdjustment'])->name('inventory.cost-adjustment');
            Route::post('inventory/customer-returns/{invoice}', [InventoryActionController::class, 'customerReturn'])->name('inventory.customer-return');
            Route::post('inventory/supplier-returns/{receipt}', [InventoryActionController::class, 'supplierReturn'])->name('inventory.supplier-return');
            Route::get('accounting/inventory/ledger', [InventoryReportController::class, 'ledger'])->name('inventory.ledger');
            Route::get('accounting/inventory/valuation', [InventoryReportController::class, 'valuation'])->name('inventory.valuation');
            Route::get('accounting/inventory/layers', [InventoryReportController::class, 'layers'])->name('inventory.layers');
            Route::get('accounting/inventory/items/{item}/layers', [InventoryReportController::class, 'layers'])->name('inventory.item-layers');
            Route::get('accounting/inventory/cogs', [InventoryReportController::class, 'cogs'])->name('inventory.cogs');
            Route::get('accounting/inventory/low-stock', [InventoryReportController::class, 'lowStock'])->name('inventory.low-stock');
            Route::get('accounting/inventory/reconciliation', [InventoryReportController::class, 'reconciliation'])->name('inventory.reconciliation');
            Route::apiResource('banking/accounts', FinancialAccountController::class)
                ->parameters(['accounts' => 'financial_account'])
                ->names('banking.accounts')
                ->only(['index', 'store', 'show', 'update']);
            Route::get('banking/statement-imports', [BankStatementImportController::class, 'index']);
            Route::post('banking/statement-imports/preview', [BankStatementImportController::class, 'preview'])->middleware('throttle:sensitive');
            Route::post('banking/statement-imports/{statement_import}/confirm', [BankStatementImportController::class, 'confirm'])->middleware('throttle:sensitive');
            Route::get('banking/transactions', [BankTransactionController::class, 'index']);
            Route::get('banking/transactions/{bank_transaction}/suggestions', [BankTransactionController::class, 'suggestions']);
            Route::post('banking/transactions/{bank_transaction}/match', [BankTransactionController::class, 'match']);
            Route::post('banking/matches/{match}/unmatch', [BankTransactionController::class, 'unmatch']);
            Route::post('banking/transactions/{bank_transaction}/classify', [BankTransactionController::class, 'classify']);
            Route::post('banking/transactions/{bank_transaction}/customer-receipt', [BankTransactionController::class, 'customerReceipt']);
            Route::post('banking/transactions/{bank_transaction}/supplier-payment', [BankTransactionController::class, 'supplierPayment']);
            Route::post('banking/cash-transactions', [BankTransactionController::class, 'cash']);
            Route::post('banking/internal-transfers', [BankTransactionController::class, 'transfer']);
            Route::get('banking/reconciliations', [BankReconciliationController::class, 'index']);
            Route::post('banking/reconciliations', [BankReconciliationController::class, 'store']);
            Route::get('banking/reconciliations/{reconciliation}', [BankReconciliationController::class, 'show']);
            Route::post('banking/reconciliations/{reconciliation}/complete', [BankReconciliationController::class, 'complete']);
            Route::post('banking/reconciliations/{reconciliation}/reopen', [BankReconciliationController::class, 'reopen']);
            Route::get('banking/settlements', [GatewaySettlementController::class, 'index']);
            Route::post('banking/settlements', [GatewaySettlementController::class, 'store']);
            Route::get('banking/settlements/{settlement}', [GatewaySettlementController::class, 'show']);
            Route::post('banking/settlements/{settlement}/post', [GatewaySettlementController::class, 'post']);
            Route::get('banking/cash-position', [CashFlowController::class, 'current']);
            Route::get('banking/cash-forecast', [CashFlowController::class, 'forecast']);
            Route::get('banking/cash-movement', [CashFlowController::class, 'movement']);
            Route::get('banking/accounts/{financial_account}/bank-gl', [CashFlowController::class, 'bankGl']);
            Route::apiResource('planning/fiscal-years', FiscalYearController::class)->only(['index', 'store', 'show'])->parameters(['fiscal-years' => 'fiscalYear'])->names('planning.fiscal-years');
            Route::post('planning/budgets/{budget}/submit', [BudgetController::class, 'submit']);
            Route::post('planning/budgets/{budget}/approve', [BudgetController::class, 'approve']);
            Route::post('planning/budgets/{budget}/activate', [BudgetController::class, 'activate']);
            Route::post('planning/budgets/{budget}/revise', [BudgetController::class, 'revise']);
            Route::get('planning/budgets/{budget}/actual', [BudgetController::class, 'actual']);
            Route::apiResource('planning/budgets', BudgetController::class)->only(['index', 'store', 'show', 'update'])->names('planning.budgets');
            Route::post('planning/forecasts/{forecast}/activate', [ForecastController::class, 'activate']);
            Route::get('planning/forecasts/{forecast}/projection', [ForecastController::class, 'projection']);
            Route::apiResource('planning/forecasts', ForecastController::class)->only(['index', 'store', 'show', 'update'])->names('planning.forecasts');
            Route::get('accounting/close/history', [AccountingCloseController::class, 'history']);
            Route::get('accounting/periods/{period}/readiness', [AccountingCloseController::class, 'readiness']);
            Route::post('accounting/periods/{period}/close', [AccountingCloseController::class, 'closePeriod']);
            Route::post('accounting/periods/{period}/reopen', [AccountingCloseController::class, 'reopenPeriod']);
            Route::get('accounting/fiscal-years/{fiscalYear}/year-end-preview', [AccountingCloseController::class, 'yearEndPreview']);
            Route::post('accounting/fiscal-years/{fiscalYear}/close', [AccountingCloseController::class, 'closeFiscalYear']);
            Route::post('accounting/fiscal-years/{fiscalYear}/reopen', [AccountingCloseController::class, 'reopenFiscalYear']);
            Route::get('payroll/statutory-rules', [PayrollComponentController::class, 'statutoryRules'])->name('payroll.statutory-rules.index');
            Route::post('payroll/statutory-rules', [PayrollComponentController::class, 'storeStatutoryRule'])->name('payroll.statutory-rules.store');
            Route::patch('payroll/components/{component}/deactivate', [PayrollComponentController::class, 'deactivate'])->name('payroll.components.deactivate');
            Route::apiResource('payroll/components', PayrollComponentController::class)->only(['index', 'store', 'show', 'update'])->names('payroll.components');
            Route::get('payroll/employees/{employee}/profiles', [EmployeePayrollProfileController::class, 'index'])->name('payroll.employee-profiles.index');
            Route::post('payroll/employees/{employee}/profiles', [EmployeePayrollProfileController::class, 'store'])->name('payroll.employee-profiles.store');
            Route::get('payroll/employees/{employee}/profiles/{profile}', [EmployeePayrollProfileController::class, 'show'])->name('payroll.employee-profiles.show');
            Route::apiResource('payroll/employees', EmployeeController::class)->only(['index', 'store', 'show', 'update'])->names('payroll.employees');
            Route::apiResource('payroll/periods', PayrollPeriodController::class)->only(['index', 'store', 'show'])->names('payroll.periods');
            Route::post('payroll/batches/{batch}/calculate', [PayrollBatchController::class, 'calculate'])->name('payroll.batches.calculate');
            Route::post('payroll/batches/{batch}/recalculate', [PayrollBatchController::class, 'recalculate'])->name('payroll.batches.recalculate');
            Route::post('payroll/batches/{batch}/review', [PayrollBatchController::class, 'review'])->name('payroll.batches.review');
            Route::post('payroll/batches/{batch}/approve', [PayrollBatchController::class, 'approve'])->name('payroll.batches.approve');
            Route::post('payroll/batches/{batch}/post', [PayrollBatchController::class, 'post'])->name('payroll.batches.post');
            Route::post('payroll/batches/{batch}/reverse', [PayrollBatchController::class, 'reverse'])->name('payroll.batches.reverse');
            Route::get('payroll/batches/{batch}/posting-preview', [PayrollBatchController::class, 'preview'])->name('payroll.batches.posting-preview');
            Route::get('payroll/batches/{batch}/entries', [PayrollEntryController::class, 'index'])->name('payroll.entries.index');
            Route::get('payroll/entries/{entry}', [PayrollEntryController::class, 'show'])->name('payroll.entries.show');
            Route::post('payroll/entries/{entry}/adjustments', [PayrollEntryController::class, 'adjust'])->name('payroll.entries.adjust');
            Route::get('payroll/entries/{entry}/payslip', [PayrollEntryController::class, 'payslip'])->name('payroll.entries.payslip');
            Route::apiResource('payroll/batches', PayrollBatchController::class)->only(['index', 'store', 'show'])->names('payroll.batches');
            Route::get('payroll/payments', [PayrollPaymentController::class, 'index'])->name('payroll.payments.index');
            Route::post('payroll/batches/{batch}/payments', [PayrollPaymentController::class, 'store'])->name('payroll.payments.store');
            Route::post('payroll/entries/{entry}/payments', [PayrollPaymentController::class, 'payEntry'])->name('payroll.entry-payments.store');
            Route::get('payroll/liabilities', [PayrollLiabilityController::class, 'index'])->name('payroll.liabilities.index');
            Route::post('payroll/liability-settlements', [PayrollLiabilityController::class, 'store'])->name('payroll.liability-settlements.store');
            Route::get('payroll/liability-settlements', [PayrollLiabilityController::class, 'history'])->name('payroll.liability-settlements.index');
            Route::get('payroll/reports/register/{batch}', [PayrollReportController::class, 'register'])->name('payroll.reports.register');
            Route::get('payroll/reports/summary', [PayrollReportController::class, 'summary'])->name('payroll.reports.summary');
            Route::get('payroll/reports/liabilities', [PayrollReportController::class, 'liabilities'])->name('payroll.reports.liabilities');
            Route::get('payroll/reports/employees/{employee}', [PayrollReportController::class, 'employeeHistory'])->name('payroll.reports.employee-history');
            Route::get('payroll/reports/components', [PayrollReportController::class, 'components'])->name('payroll.reports.components');
            Route::get('payroll/reports/reconciliation/{batch}', [PayrollReportController::class, 'reconciliation'])->name('payroll.reports.reconciliation');
            Route::get('crm/owners', [CrmReportController::class, 'owners'])->name('crm.owners');
            Route::get('crm/dashboard', [CrmReportController::class, 'dashboard'])->name('crm.dashboard');
            Route::get('crm/reports/pipeline', [CrmReportController::class, 'pipeline'])->name('crm.reports.pipeline');
            Route::get('crm/reports/activities', [CrmReportController::class, 'activities'])->name('crm.reports.activities');
            Route::get('crm/accounts/{account}/customer-matches', [CrmAccountController::class, 'customerMatches'])->name('crm.accounts.customer-matches');
            Route::post('crm/accounts/{account}/customer-handoff', [CrmAccountController::class, 'customerHandoff'])->name('crm.accounts.customer-handoff');
            Route::apiResource('crm/accounts', CrmAccountController::class)->parameters(['accounts' => 'account'])->names('crm.accounts');
            Route::apiResource('crm/contacts', CrmContactController::class)->parameters(['contacts' => 'contact'])->names('crm.contacts');
            Route::post('crm/leads/{lead}/transition', [CrmLeadController::class, 'transition'])->name('crm.leads.transition');
            Route::post('crm/leads/{lead}/convert', [CrmLeadController::class, 'convert'])->middleware('throttle:sensitive')->name('crm.leads.convert');
            Route::apiResource('crm/leads', CrmLeadController::class)->parameters(['leads' => 'lead'])->names('crm.leads');
            Route::apiResource('crm/pipelines', CrmPipelineController::class)->parameters(['pipelines' => 'pipeline'])->names('crm.pipelines');
            Route::post('crm/deals/{deal}/transition', [CrmDealController::class, 'transition'])->name('crm.deals.transition');
            Route::post('crm/deals/{deal}/customer-handoff', [CrmDealController::class, 'customerHandoff'])->name('crm.deals.customer-handoff');
            Route::apiResource('crm/deals', CrmDealController::class)->parameters(['deals' => 'deal'])->names('crm.deals');
            Route::post('crm/activities/{activity}/transition', [CrmActivityController::class, 'transition'])->name('crm.activities.transition');
            Route::apiResource('crm/activities', CrmActivityController::class)->parameters(['activities' => 'activity'])->names('crm.activities');
            Route::post('crm/tags/attach', [CrmTagController::class, 'attach'])->name('crm.tags.attach');
            Route::apiResource('crm/tags', CrmTagController::class)->parameters(['tags' => 'tag'])->names('crm.tags');
            Route::get('crm/imports', [CrmImportController::class, 'index'])->name('crm.imports.index');
            Route::post('crm/imports/preview', [CrmImportController::class, 'preview'])->middleware('throttle:sensitive')->name('crm.imports.preview');
            Route::get('crm/imports/{import}', [CrmImportController::class, 'show'])->name('crm.imports.show');
            Route::post('crm/imports/{import}/confirm', [CrmImportController::class, 'confirm'])->middleware('throttle:sensitive')->name('crm.imports.confirm');
            Route::get('crm/score-rules', [CrmScoreController::class, 'index'])->name('crm.score-rules.index');
            Route::post('crm/score-rules', [CrmScoreController::class, 'store'])->name('crm.score-rules.store');
            Route::put('crm/score-rules/{rule}', [CrmScoreController::class, 'update'])->name('crm.score-rules.update');
            Route::delete('crm/score-rules/{rule}', [CrmScoreController::class, 'destroy'])->name('crm.score-rules.destroy');
            Route::post('crm/scores/{type}/{id}/recalculate', [CrmScoreController::class, 'recalculate'])->whereIn('type', ['lead', 'deal'])->name('crm.scores.recalculate');
            Route::get('outreach/providers', [EmailProviderConnectionController::class, 'index'])->name('outreach.providers.index');
            Route::post('outreach/providers', [EmailProviderConnectionController::class, 'store'])->name('outreach.providers.store');
            Route::get('outreach/providers/{connection}', [EmailProviderConnectionController::class, 'show'])->name('outreach.providers.show');
            Route::patch('outreach/providers/{connection}', [EmailProviderConnectionController::class, 'update'])->name('outreach.providers.update');
            Route::post('outreach/providers/{connection}/verify', [EmailProviderConnectionController::class, 'verify'])->middleware('throttle:sensitive')->name('outreach.providers.verify');
            Route::post('outreach/providers/{connection}/disconnect', [EmailProviderConnectionController::class, 'disconnect'])->name('outreach.providers.disconnect');
            Route::post('outreach/providers/{connection}/sync-replies', [EmailProviderConnectionController::class, 'syncReplies'])->middleware('throttle:sensitive')->name('outreach.providers.sync-replies');
            Route::get('outreach/identities', [EmailSendingIdentityController::class, 'index'])->name('outreach.identities.index');
            Route::post('outreach/identities', [EmailSendingIdentityController::class, 'store'])->name('outreach.identities.store');
            Route::patch('outreach/identities/{identity}', [EmailSendingIdentityController::class, 'update'])->name('outreach.identities.update');
            Route::get('outreach/templates', [EmailTemplateController::class, 'index'])->name('outreach.templates.index');
            Route::post('outreach/templates', [EmailTemplateController::class, 'store'])->name('outreach.templates.store');
            Route::patch('outreach/templates/{template}', [EmailTemplateController::class, 'update'])->name('outreach.templates.update');
            Route::post('outreach/templates/{template}/preview', [EmailTemplateController::class, 'preview'])->name('outreach.templates.preview');
            Route::get('outreach/sequences', [OutreachSequenceController::class, 'index'])->name('outreach.sequences.index');
            Route::post('outreach/sequences', [OutreachSequenceController::class, 'store'])->name('outreach.sequences.store');
            Route::get('outreach/sequences/{sequence}', [OutreachSequenceController::class, 'show'])->name('outreach.sequences.show');
            Route::put('outreach/sequences/{sequence}', [OutreachSequenceController::class, 'update'])->name('outreach.sequences.update');
            Route::post('outreach/sequences/{sequence}/transition', [OutreachSequenceController::class, 'transition'])->name('outreach.sequences.transition');
            Route::post('outreach/sequences/{sequence}/enrollments', [OutreachEnrollmentController::class, 'store'])->middleware('throttle:sensitive')->name('outreach.enrollments.store');
            Route::get('outreach/enrollments', [OutreachEnrollmentController::class, 'index'])->name('outreach.enrollments.index');
            Route::post('outreach/enrollments/{enrollment}/transition', [OutreachEnrollmentController::class, 'transition'])->name('outreach.enrollments.transition');
            Route::get('outreach/messages', [OutreachMessageController::class, 'index'])->name('outreach.messages.index');
            Route::get('outreach/messages/{message}', [OutreachMessageController::class, 'show'])->name('outreach.messages.show');
            Route::post('outreach/messages/{message}/retry', [OutreachMessageController::class, 'retry'])->middleware('throttle:sensitive')->name('outreach.messages.retry');
            Route::get('outreach/suppressions', [OutreachSuppressionController::class, 'index'])->name('outreach.suppressions.index');
            Route::post('outreach/suppressions', [OutreachSuppressionController::class, 'store'])->name('outreach.suppressions.store');
            Route::delete('outreach/suppressions/{suppression}', [OutreachSuppressionController::class, 'destroy'])->name('outreach.suppressions.destroy');
            Route::get('outreach/reports', [OutreachReportController::class, 'show'])->name('outreach.reports.show');
            Route::post('outreach/ai/draft', [OutreachReportController::class, 'aiDraft'])->middleware('throttle:sensitive')->name('outreach.ai.draft');
        });
    });
});
